from django.db import models
from django.utils.translation import gettext_lazy as _

class student_1 (models.Model):
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)
  
     
     
    
class student_2 (models.Model): 
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)

class student_3 (models.Model):
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)
      
      
      
class student_4 (models.Model):
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)
            
            
class student_5 (models.Model):
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)
                  
                  
class student_6 (models.Model):
    school_name = models.CharField(_("School Name"), max_length=255)
    year = models.DateField(_("Year"))
    StudentID = models.CharField(_("Student ID"), max_length=255)
    Firstname = models.CharField(_("First Name"), max_length=255)
    Lastname = models.CharField(_("Last Name"), max_length=255)
    Yearlevel = models.CharField(_("Year Level"), max_length=255)
    Class = models.CharField(_("Class"), max_length=255)
    Subject = models.CharField(_("Subject"), max_length=255)
    Answer = models.CharField(_("Answer"), max_length=255)
    Correctanswers = models.CharField(_("Correct Answers"), max_length=255)
    Questionnumber = models.CharField(_("Question Number"), max_length=255)
    Subjectcontents = models.CharField(_("Subject Contents"), max_length=255)
    Assesmentareas = models.CharField(_("Assessment Areas"), max_length=255)
    Sydneycorrectcountpercentage = models.FloatField(_("Sydney Correct Count Percentage"))
    Sydneyaveragescore = models.FloatField(_("Sydney Average Score"))
    Sydneyparticipants = models.IntegerField(_("Sydney Participants"))
    Studentscore = models.FloatField(_("Student Total Assessed"))
    Studenttotalassed = models.CharField(_("Student Total Assessed"), max_length=255)
    Studentareaassed = models.CharField(_("Student Area Assessed"), max_length=255)
    Participant = models.CharField(_("Participant"), max_length=255)
    Correctanswerpercentageperclass = models.FloatField(_("Correct Answer Percentage per Class"))
    Averagescore = models.FloatField(_("Average Score"))
    Schoolpercentile = models.CharField(_("School Percentile"), max_length=255)
    Sydneypercentile = models.CharField(_("Sydney Percentile"), max_length=255)
    Strengthstatus = models.CharField(_("Strength Status"), max_length=255)
    Highdistinctcount = models.IntegerField(_("High Distinct Count"))
    Distinctcount = models.IntegerField(_("Distinct Count"))
    Creditcount = models.IntegerField(_("Credit Count"))
    Participantcount = models.IntegerField(_("Participant Count"))
    Awardistintion = models.CharField(_("Award Distinction"), max_length=255)